- name: Prepare and Run Scraper
        working-directory: ./inr
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        run: |
          chmod +x setup.sh
          ./setup.sh

      - name: Merge and Upload Results
        working-directory: ./inr
        env:
          MEGA_USER: ${{ secrets.MEGA_USER }}
          MEGA_PASS: ${{ secrets.MEGA_PASS }}
        run: |
          LATEST_BATCH=$(ls -td ./results/*/ | head -1 | xargs basename)
          ./manager.sh finalize "$LATEST_BATCH"
